### ISSUE TITLE
Issues loading client with mod installed

### ISSUE THREAD

**Issue by Ol2gud** [Dekunutter/CherryBlossomGrotto#43]
Hey, i know this is probably posted here alot, but ive downloaded the required mods (unless im stupid and and smth wrong) and the game crashes without loading, so i removed my other mods except optifine and it still didnt load, meaning its not a compatibility issue.... i think. the exit code is -1 and the crash report is here:

---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 2023-03-18 20:08:54
Description: Rendering overlay

java.lang.NoSuchMethodError: 'net.minecraft.network.chat.FormattedText net.minecraft.client.gui.Font.ellipsize(net.minecraft.network.chat.FormattedText, int)'
	at net.minecraftforge.client.gui.widget.ExtendedButton.m_6303_(ExtendedButton.java:54) ~[forge-1.19.3-44.1.23-universal.jar%23197!/:?] {re:classloading}
	at net.minecraft.client.gui.components.AbstractWidget.m_86412_(AbstractWidget.java:74) ~[client-1.19.3-20221207.122022-srg.jar%23192!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.gui.LoadingErrorScreen.lambda$render$4(LoadingErrorScreen.java:86) ~[forge-1.19.3-44.1.23-universal.jar%23197!/:?] {re:classloading}
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?] {}
	at net.minecraftforge.client.gui.LoadingErrorScreen.m_86412_(LoadingErrorScreen.java:86) ~[forge-1.19.3-44.1.23-universal.jar%23197!/:?] {re:classloading}
	at net.minecraft.client.gui.screens.LoadingOverlay.m_86412_(LoadingOverlay.java:109) ~[client-1.19.3-20221207.122022-srg.jar%23192!/:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:1332) ~[client-1.19.3-20221207.122022-srg.jar%23192!/:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1135) ~[client-1.19.3-20221207.122022-srg.jar%23192!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:fallingleaves.mixins.json:MinecraftClientMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:713) ~[client-1.19.3-20221207.122022-srg.jar%23192!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:fallingleaves.mixins.json:MinecraftClientMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[1.19.3-forge-44.1.23.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:51) ~[1.19.3-forge-44.1.23.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.3-44.1.23.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraftforge.client.gui.widget.ExtendedButton.m_6303_(ExtendedButton.java:54) ~[forge-1.19.3-44.1.23-universal.jar%23197!/:?] {re:classloading}
	at net.minecraft.client.gui.components.AbstractWidget.m_86412_(AbstractWidget.java:74) ~[client-1.19.3-20221207.122022-srg.jar%23192!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.gui.LoadingErrorScreen.lambda$render$4(LoadingErrorScreen.java:86) ~[forge-1.19.3-44.1.23-universal.jar%23197!/:?] {re:classloading}
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?] {}
	at net.minecraftforge.client.gui.LoadingErrorScreen.m_86412_(LoadingErrorScreen.java:86) ~[forge-1.19.3-44.1.23-universal.jar%23197!/:?] {re:classloading}
	at net.minecraft.client.gui.screens.LoadingOverlay.m_86412_(LoadingOverlay.java:109) ~[client-1.19.3-20221207.122022-srg.jar%23192!/:?] {re:classloading,xf:OptiFine:default}
-- Overlay render details --
Details:
	Overlay name: net.minecraft.client.gui.screens.LoadingOverlay
Stacktrace:
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:1332) ~[client-1.19.3-20221207.122022-srg.jar%23192!/:?] {re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1135) ~[client-1.19.3-20221207.122022-srg.jar%23192!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:fallingleaves.mixins.json:MinecraftClientMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:713) ~[client-1.19.3-20221207.122022-srg.jar%23192!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:fallingleaves.mixins.json:MinecraftClientMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[1.19.3-forge-44.1.23.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:51) ~[1.19.3-forge-44.1.23.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.3-44.1.23.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, file/Default-Dark-Mode-1.19.3-0.8-000000-0-000000-AAAAAA-(v1.4.0).zip
Stacktrace:
	at net.minecraft.client.ResourceLoadStateTracker.m_168562_(ResourceLoadStateTracker.java:49) ~[client-1.19.3-20221207.122022-srg.jar%23192!/:?] {re:classloading}
	at net.minecraft.client.Minecraft.m_91354_(Minecraft.java:2328) ~[client-1.19.3-20221207.122022-srg.jar%23192!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:fallingleaves.mixins.json:MinecraftClientMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:730) ~[client-1.19.3-20221207.122022-srg.jar%23192!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:fallingleaves.mixins.json:MinecraftClientMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[1.19.3-forge-44.1.23.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:51) ~[1.19.3-forge-44.1.23.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.3-44.1.23.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.8.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}

-- System Details --
Details:
	Minecraft Version: 1.19.3
	Minecraft Version ID: 1.19.3
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 318057920 bytes (303 MiB) / 771751936 bytes (736 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
	Identifier: Intel64 Family 6 Model 140 Stepping 1
	Microarchitecture: Tiger Lake
	Frequency (GHz): 2.42
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Intel(R) Iris(R) Xe Graphics
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x9a49
	Graphics card #0 versionInfo: DriverVersion=30.0.101.1029
	Graphics card #1 name: NVIDIA GeForce GTX 1650 Ti with Max-Q Design
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 4095.00
	Graphics card #1 deviceId: 0x1f95
	Graphics card #1 versionInfo: DriverVersion=31.0.15.3118
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.20
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 18565.99
	Virtual memory used (MB): 16064.67
	Swap memory total (MB): 2432.00
	Swap memory used (MB): 127.17
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: 1.19.3-forge-44.1.23
	Backend library: LWJGL version 3.3.1 build 7
	Backend API: NVIDIA GeForce GTX 1650 Ti with Max-Q Design/PCIe/SSE2 GL version 3.2.0 NVIDIA 531.18, NVIDIA Corporation
	Window size: 854x480
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, file/Default-Dark-Mode-1.19.3-0.8-000000-0-000000-AAAAAA-(v1.4.0).zip
	Current Language: English (US)
	CPU: 8x 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
	OptiFine Version: OptiFine_1.19.3_HD_U_I2_pre5
	OptiFine Build: 20230219-203817
	Render Distance Chunks: 10
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: (internal)
	OpenGlVersion: 3.2.0 NVIDIA 531.18
	OpenGlRenderer: NVIDIA GeForce GTX 1650 Ti with Max-Q Design/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8
	ModLauncher: 10.0.8+10.0.8+main.0ef7e830
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.3.jar eventbus PLUGINSERVICE 
		fmlloader-1.19.3-44.1.23.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.19.3-44.1.23.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.19.3-44.1.23.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.19.3-44.1.23.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.19.3-44.1.23.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.8.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar OptiFine TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.19.3-20221207.122022-srg.jar             |Minecraft                     |minecraft                     |1.19.3              |COMMON_SET|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		immersive_paintings-0.5.0+1.19.3-forge.jar        |Immersive Paintings           |immersive_paintings           |0.5.0+1.19.3        |COMMON_SET|Manifest: NOSIGNATURE
		badpackets-forge-0.3.4.jar                        |Bad Packets                   |badpackets                    |0.3.4               |COMMON_SET|Manifest: NOSIGNATURE
		horsecombatcontrols-1.19.3-1.0.0.jar              |Horse Combat Controls         |horsecombatcontrols           |1.19.3-1.0.0        |COMMON_SET|Manifest: NOSIGNATURE
		voicechat-forge-1.19.3-2.3.28.jar                 |Simple Voice Chat             |voicechat                     |1.19.3-2.3.28       |COMMON_SET|Manifest: NOSIGNATURE
		TerraBlender-forge-1.19.3-2.1.0.134.jar           |TerraBlender                  |terrablender                  |2.1.0.134           |COMMON_SET|Manifest: NOSIGNATURE
		cherryblossomgrotto-1.4.0-v1.19.3.jar             |Cherry Blossom Grotto         |cherryblossomgrotto           |1.4.0               |ERROR     |Manifest: NOSIGNATURE
		trashslot-forge-1.19.3-13.0.1.jar                 |TrashSlot                     |trashslot                     |13.0.1              |COMMON_SET|Manifest: NOSIGNATURE
		eatinganimation-1.19.3-4.0.0.jar                  |Eating Animation              |eatinganimation               |4.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		balm-forge-1.19.3-5.0.3.jar                       |Balm                          |balm                          |5.0.3               |COMMON_SET|Manifest: NOSIGNATURE
		jei-1.19.3-forge-12.3.0.21.jar                    |Just Enough Items             |jei                           |12.3.0.21           |COMMON_SET|Manifest: NOSIGNATURE
		callablehorses-1.19.3-1.2.2.5.jar                 |Callable Horses               |callablehorses                |1.2.2.5             |COMMON_SET|Manifest: 8c:03:ac:7d:21:62:65:e2:83:91:f3:22:57:99:ed:75:78:1e:db:de:03:99:ef:53:3b:59:95:18:01:bc:84:a9
		wthit-forge-6.2.0.jar                             |wthit                         |wthit                         |6.2.0               |COMMON_SET|Manifest: NOSIGNATURE
		cloth-config-9.0.94-forge.jar                     |Cloth Config v9 API           |cloth_config                  |9.0.94              |COMMON_SET|Manifest: NOSIGNATURE
		forge-1.19.3-44.1.23-universal.jar                |Forge                         |forge                         |44.1.23             |COMMON_SET|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		appleskin-forge-mc1.19-2.4.2.jar                  |AppleSkin                     |appleskin                     |2.4.2+mc1.19        |COMMON_SET|Manifest: NOSIGNATURE
		InvMove-1.19-0.8.2-Forge.jar                      |InvMove                       |invmove                       |0.8.2               |COMMON_SET|Manifest: NOSIGNATURE
		soundphysics-forge-1.19.3-1.0.18.jar              |Sound Physics Remastered      |sound_physics_remastered      |1.19.3-1.0.18       |COMMON_SET|Manifest: NOSIGNATURE
		RealisticSleep-1.19-2.1.0.2-universal.jar         |Realistic Sleep               |realisticsleep                |1.19-2.1.0.2        |COMMON_SET|Manifest: NOSIGNATURE
		Fallingleaves-1.19.3-2.0.0.jar                    |Falling Leaves                |fallingleaves                 |2.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		dungeon-now-loading-17.1-v1.19.jar                |Dungeon Now Loading           |dungeonnowloading             |1.19-17.1           |COMMON_SET|Manifest: NOSIGNATURE
	Crash Report UUID: 3818aca0-8b64-4bc9-a491-c3877dbfe017
	FML: 44.1
	Forge: net.minecraftforge:44.1.23

**Comment by Dekunutter** [comment]
Hi, thanks for reporting this issue. Looks like the crash report you pasted in indicates that you do have a lot of other mods installed alongside cherryblossomgrotto. Currently I'm trying to replicate the issue and I'm getting a crash too but doesnt seem to be the same crash as what you've posted. If I use all the mods listed near the bottom of your crash report but remove cherryblossomgrotto, it still crashes. So the evidence so far looks like this may be an issue with another mod

**Comment by Dekunutter** [comment]
I noticed you had closed this issue, I reopened since I assumed it was unintentional but feel free to close again if your problem was resolved already!

**Comment by Ol2gud** [comment]
> I noticed you had closed this issue, I reopened since I assumed it was unintentional but feel free to close again if your problem was resolved already!

The issue was that I was using a Fabric version of Gekolib I took from a Fabric mod pack I had made, instead of the Forge one for pack i’m currently working on. Sorry for opening an issue for such a dumb mistake. Love the mod, keep up the great work!
